export enum QueryKeys {
  USER = 'USER',
  LOGIN = 'LOGIN',
  WORKSHOP = 'WORKSHOP',
  LIST_WORKSHOPS = 'LIST_WORKSHOPS',
  CREATE_USER = 'CREATE_USER',
  CREATE_WORKSHOP_USER = 'CREATE_WORKSHOP_USER',
  AVAILABLE_SLOTS = 'AVAILABLE_SLOTS',
  APPOINTMENT = 'APPOINTMENT',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  LIST_APPOINTMENT = 'LIST_APPOINTMENT',
}

export enum StorageKeys {
  ACCESS_TOKEN = 'access_token',
  USER = 'user',
}
